apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "simple-kubernetes-webhook.acme.com"
webhooks:
  - name: "simple-kubernetes-webhook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: simple-kubernetes-webhook
        path: /validate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzakNDQWNZQ0NRRC81eXFkVmFJTGN6QU5CZ2tx
        aGtpRzl3MEJBUXNGQURBeE1Rc3dDUVlEVlFRR0V3SkIKVlRFaU1DQUdBMVVFQXd3WmMybHRjR3hsTFd0
        MVltVnlibVYwWlhNdGQyVmlhRzl2YXpBZUZ3MHlNakV5TVRVeApNVE00TURGYUZ3MHlNekV5TVRVeE1U
        TTRNREZhTURFeEN6QUpCZ05WQkFZVEFrRlZNU0l3SUFZRFZRUUREQmx6CmFXMXdiR1V0YTNWaVpYSnVa
        WFJsY3kxM1pXSm9iMjlyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVB
        eUJmS1hDVGY4NzZHTnRpUjlvamdWYmwwa1BBRXNqdlhEQlEyQkxVdW5qcExGcEYwa0NMcgp5V05aWmVU
        QVY1T0ZoRmlFWEZsSVNKWks0SDVYTmsvRFFCS2tGSFFDSUVTb2NhRU9OSlFqQ0FoNUdzQWFqQXNmCmRQ
        eFRPZkwwYmxWVFpVSGMzWkUvL1FOVTIrRDRVNGpURVduYk5aa1lnR3BGdEdLeEVoSG1kMVhsOHdNUFZv
        R0IKR2JVYk1odGpvc0daczMzQ08vNlJOWDZIeVk4VjRSbmh0Q1kvVVVrTG9LdWhKd0llRzdsS3kvVFFi
        ZnNSMWhGWgpMb2hRQUduSXlNTDlVR2FKMXVhVm4zZWFsMGFDamxpWnNWaG9TbVUxWk91dUp0b2J5eGtP
        WTl3ckJQcjVIVWM4Cm5BTDFEa3FSajNBeXdaNURsTEVJdnMzYnhubytIKzVIdXdJREFRQUJNQTBHQ1Nx
        R1NJYjNEUUVCQ3dVQUE0SUIKQVFCbG9HalM2UjIxT0Ezd3ZFWnVRcDFFK0JqdzZtZ2txcTVqZmhuNzlS
        WENpd1NzTTRHeERzZEJoNFd3SEVjRQo0MjIrTUhzUDdQV3J6aEdYenVVMEFpdGZ1SktyRjJGWFdFSnNP
        S1Q2ckhZc1p2ZXRuSFU3WCs0aGdENEticGQwCnhZbHQvWGM4cWRYelgrRWtWcmdpY29SZmVsbVdHcDg3
        K2RuSklkU1ZuZ1NLanZkajQrM0E1ZTBkalY1QlY4aVYKRnJNQVZQamRTYU5LWkM4Y3lmRnZocitRSGQ2
        THF5TUFqWGwxY1g3OWIyWTZSZ3hHMVAzeU5vRWZWbVp0UmhNYwpFTlNxTGdKblZ6dU1lb3U1TURnMUpT
        cDJVUXd6SzV1UkhtQ1FhZExyRUhFZnh5NlRIMG1aeXU0cWRQLzFzQzdhCk8zMzNMVjdwREFxejlSaWZx
        SzZDRWwwZQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
